import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastProviderWrapper } from "./utils/Toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DMS",
  description: "Generated by create next app",
  icons: {
    icon: "/main.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* <ToastProviderWrapper> */}
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      {/* </ToastProviderWrapper> */}
    </>
  );
}
