import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";

import "./globals.css";
import Providers from "@/state/provider";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "DMS",
  description: "Generated by imran",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Providers> {children}</Providers>

            <Toaster richColors closeButton />
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
